<?php

namespace HistoriqueGlobalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Historique_GlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_GlobalRepository extends EntityRepository
{
}
