<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Compte_PaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Compte_PaieRepository extends EntityRepository
{
}
