<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationDemandeRepository extends EntityRepository
{
}
