<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Demande_AvanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Demande_AvanceRepository extends EntityRepository
{
    public function findByMoisAnne($slug, $dateDebut, $dateFin){

        $qb = $this->createQueryBuilder('dmdAvc');

        $qb->join('dmdAvc.empoye', 'employe')
            ->where('employe.slug= :slug')
            ->andWhere('dmdAvc.date >= :dateDebut')
            ->andWhere('dmdAvc.date < :dateFin')
            ->setParameter('slug', $slug)
            ->setParameter('dateDebut', $dateDebut)
            ->setParameter('dateFin', $dateFin)
            ->orderBy('dmdAvc.date', 'ASC');

        return $qb->getQuery()
            ->getResult()
            ;


    }
}
