<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DemandePaiementCongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandePaiementCongeRepository extends EntityRepository
{
}
