<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Historique_AvanceSpecialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_AvanceSpecialRepository extends EntityRepository
{
}
