<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Historique_PaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_PaieRepository extends EntityRepository
{
    public function findByMoisAnne($slug, $dateDebut, $dateFin){

        $qb = $this->createQueryBuilder('hist');

        $qb->join('hist.comptePaie', 'comptePaie')
            ->where('comptePaie.slug = :slug')
            ->andWhere('hist.date >= :dateDebut')
            ->andWhere('hist.date < :dateFin')
            ->setParameter('slug', $slug)
            ->setParameter('dateDebut', $dateDebut)
            ->setParameter('dateFin', $dateFin)
            ->orderBy('hist.date', 'ASC');

        return $qb->getQuery()
            ->getResult()
        ;


    }

}
