<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Historique_Demande_AvanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_Demande_AvanceRepository extends EntityRepository
{
}
