<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Numero_demandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Numero_demandeRepository extends EntityRepository
{
}
