<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NumeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeroRepository extends EntityRepository
{
}
