<?php

namespace PaieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VerificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerificationRepository extends EntityRepository
{
}
