api_route_public:
    resource: "@HistoriqueGlobalBundle/Controller/HissabAPIController.php"
    type:     annotation

api_route_externe:
  resource: "@HistoriqueGlobalBundle/Controller/ExterneAPIController.php"
  type:     annotation

grp_global:
    resource: "@HistoriqueGlobalBundle/Resources/config/routing.yml"
    prefix:   /

paie:
    resource: "@PaieBundle/Resources/config/routing.yml"
    prefix:   /paiement

presence:
    resource: "@PresenceBundle/Resources/config/routing.yml"
    prefix:   /ressources-humaines

document:
    resource: "@DocumentBundle/Resources/config/routing.yml"
    prefix:   /document

employe:
    resource: "@EmployeBundle/Resources/config/routing.yml"
    prefix:   /gestion/employer

admin_utilisateur:
    resource: "@UserBundle/Resources/config/routing_admin.yml"
    prefix:   /admin/utilisateur

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


#Route de FOSUser
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


