# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        MPTDN\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_GRH: ROLE_USER
        ROLE_PAIE: ROLE_USER
        ROLE_RH: ROLE_USER
        ROLE_SEC: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_CLIENT, ROLE_FOURNISSEUR, ROLE_DIVERS, ROLE_ADMIN, ROLE_COMPTA, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/login$
            anonymous: true

        main_payement:
            pattern: ^/api
            anonymous: true

        main:
            pattern: ^/
            anonymous: false
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
               path: fos_user_security_logout
               target: /
            remember_me:
                key: %secret%

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
