<?php

namespace EmployeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Emp_residenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Emp_residenceRepository extends EntityRepository
{
}
