<?php

namespace PresenceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EmployeBundle\Entity\Employe;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends EntityRepository
{
    public function findNotFalseEmploye()
    {
        $qb = $this->createQueryBuilder('r');

        $qb->where('r.employe != :valeur')
            ->setParameter('valeur', false)
            ->orderBy('r.dateDebut', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }
    public function findAbsByAnnee(Employe $employe, $dateDebut, $dateFin){

        $qb = $this->createQueryBuilder('abs');

        $qb->join('abs.employe', 'employe')
            ->where('employe = :employe')
            ->andWhere('abs.dateDebut >= :dateDebut')
            ->andWhere('abs.dateRetour <= :dateFin')
            ->setParameter('employe', $employe)
            ->setParameter('dateDebut', $dateDebut)
            ->setParameter('dateFin', $dateFin)
            ->orderBy('abs.dateDebut', 'ASC');

        return $qb->getQuery()
            ->getResult();

    }
}
