<?php

namespace PresenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Compte_PresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Compte_PresenceRepository extends EntityRepository
{
}
