<?php

namespace PresenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Conge_PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Conge_PermissionRepository extends EntityRepository
{
    public function findNotFalseEmploye()
    {
        $qb = $this->createQueryBuilder('r');

        $qb->where('r.employe != :valeur')
            ->setParameter('valeur', false)
            ->orderBy('r.dateDebut', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }


    public function findByMois($idEmploye, \DateTime $dateDebut, \DateTime $dateFin){
        $qb = $this->createQueryBuilder('conge');

        $qb->join('conge.employe', 'employe')
            ->where('employe.id = :idEmploye' )
            ->andWhere('conge.dateDebut >= :dateDebut')
            ->andWhere('conge.dateDebut < :dateFin')
            ->andWhere('conge.type = :conge')
            ->setParameter('idEmploye', $idEmploye)
            ->setParameter('dateDebut', $dateDebut)
            ->setParameter('dateFin', $dateFin)
            ->setParameter('conge', "Congé")
        ;

        return $qb->getQuery()->getResult();
    }

}
