<?php

namespace PresenceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Demande_CPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Demande_CPRepository extends EntityRepository
{
}
