<?php

namespace PresenceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use EmployeBundle\Entity\Employe;

/**
 * RetardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetardRepository extends EntityRepository
{
    public function findNotFalseEmploye()
    {
        $qb = $this->createQueryBuilder('r');

        $qb->where('r.employe != :valeur')
            ->setParameter('valeur', false)
            ->orderBy('r.dateHeure', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }
    public function findRetByAnnee(Employe $employe, $dateDebut, $dateFin){

        $qb = $this->createQueryBuilder('ret');

        $qb->join('ret.employe', 'employe')
            ->where('employe = :employe')
            ->andWhere('ret.dateHeure >= :dateDebut')
            ->andWhere('ret.dateHeure <= :dateFin')
            ->setParameter('employe', $employe)
            ->setParameter('dateDebut', $dateDebut)
            ->setParameter('dateFin', $dateFin)
            ->orderBy('ret.dateHeure', 'ASC');

        return $qb->getQuery()
            ->getResult();

    }
}
